name: Daily NRFI Run

on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run model
      run: python src/predict_all.py

    - name: Commit results
      run: |
        git config --global user.name "nrfi-bot"
        git add data/
        git commit -m "daily update"
        git push
